# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180222_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='relations',
        ),
        migrations.AddField(
            model_name='entry',
            name='relations',
            field=models.ManyToManyField(blank=True, related_name='_entry_relations_+', to='mainapp.Entry'),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='tags',
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mainapp.Tag'),
        ),
    ]
